Repository black7375/Firefox-UI-Fix, pull requests merged in 2021-06, with the labels that each got.

#25 Fix Minor Spelling Error for !important
  userChrome.css
Labels: bug

#75 ref: Exclude unnecessary files from zip export
  .gitattributes
Labels: Install

#78 Added missing errors
  userContent.css
Labels: Class::Icon, Component::UserContents

#84 Docfix(grammar and sentence structure) and .gitattributes polish
  .gitattributes
  README.org
Labels: Install, documentation

#96 Feat: Change New Tab button #95
  CREDITS
  icons/tab-bottom-corner-left.svg
  icons/tab-bottom-corner-right.svg
  userChrome.css
Labels: Class::Padding, Component::Tab
